// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA49mwPZNClHAj5meHIigTGBSaMjMYys48',
    appId: '1:690225929026:web:ae0c1dd05ed413a60386db',
    messagingSenderId: '690225929026',
    projectId: 'pos-foodscan',
    authDomain: 'pos-foodscan.firebaseapp.com',
    storageBucket: 'pos-foodscan.firebasestorage.app',
    measurementId: 'G-GCBV15DDPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxo0gMSjdfU1O54YIz2xsLPylbFyIFgKM',
    appId: '1:690225929026:android:63ff8504957ca8780386db',
    messagingSenderId: '690225929026',
    projectId: 'pos-foodscan',
    storageBucket: 'pos-foodscan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzBAYqrTXeMHMwNhZKm_Oz2JxlgWWAHyU',
    appId: '1:690225929026:ios:37d40809fc37dbe00386db',
    messagingSenderId: '690225929026',
    projectId: 'pos-foodscan',
    storageBucket: 'pos-foodscan.firebasestorage.app',
    iosBundleId: 'com.pos.foodscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzBAYqrTXeMHMwNhZKm_Oz2JxlgWWAHyU',
    appId: '1:690225929026:ios:8e007836fc7805310386db',
    messagingSenderId: '690225929026',
    projectId: 'pos-foodscan',
    storageBucket: 'pos-foodscan.firebasestorage.app',
    iosBundleId: 'com.example.foodscanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA49mwPZNClHAj5meHIigTGBSaMjMYys48',
    appId: '1:690225929026:web:b8bcccd84faa888d0386db',
    messagingSenderId: '690225929026',
    projectId: 'pos-foodscan',
    authDomain: 'pos-foodscan.firebaseapp.com',
    storageBucket: 'pos-foodscan.firebasestorage.app',
    measurementId: 'G-X1VLT8MQGN',
  );
}
